# 02 Provenance, schema and labels (Phase 2)
Produced by `python -I src/audit/schema_labels.py scan` and `derive`. This notebook re-reads every header directly and checks it against the saved schema.

In [1]:
import sys, json
from pathlib import Path
import pandas as pd
ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT))
R = ROOT / "results/audit"
M = ROOT / "data/manifests"
pd.set_option("display.max_rows", 80); pd.set_option("display.max_columns", 40); pd.set_option("display.width", 200)
print("project root:", ROOT.name)

project root: research_paper

In [2]:
S = json.loads((R / 'schema_by_file.json').read_text(encoding='utf-8'))['files']
pd.DataFrame([{k: s[k] for k in ['relpath','n_columns','n_rows','read_mode','source_encoding','line_ending']}
              | {'lines_not_read': s['newline_check']['lines_not_read_as_rows']} for s in S])

                                              relpath  n_columns   n_rows read_mode source_encoding line_ending  lines_not_read
0           data/raw_improved/CIC-IDS-2017/friday.csv         91   547557    strict           utf-8          LF               0
1           data/raw_improved/CIC-IDS-2017/monday.csv         91   371624    strict           utf-8          LF               0
2         data/raw_improved/CIC-IDS-2017/thursday.csv         91   362076    strict           utf-8          LF               0
3          data/raw_improved/CIC-IDS-2017/tuesday.csv         91   322078    strict           utf-8          LF               0
4        data/raw_improved/CIC-IDS-2017/wednesday.csv         91   496641    strict           utf-8          LF               0
5   data/raw_improved/CSE-CIC-IDS-2018/Friday-02-0...         91  6311371    strict           utf-8          LF               0
6   data/raw_improved/CSE-CIC-IDS-2018/Friday-16-0...         91  7390266    strict           utf-8          LF               0
7   data/raw_improved/CSE-CIC-IDS-2018/Friday-23-0...         91  5976481    strict           utf-8          LF               0
8   data/raw_improved/CSE-CIC-IDS-2018/Thursday-01...         91  6551401    strict           utf-8          LF               0
9   data/raw_improved/CSE-CIC-IDS-2018/Thursday-15...         91  5410102    strict           utf-8          LF               0
10  data/raw_improved/CSE-CIC-IDS-2018/Thursday-22...         91  6071153    strict           utf-8          LF               0
11  data/raw_improved/CSE-CIC-IDS-2018/Tuesday-20-...         91  6054702    strict           utf-8          LF               0
12  data/raw_improved/CSE-CIC-IDS-2018/Wednesday-1...         91  5898350    strict           utf-8          LF               0
13  data/raw_improved/CSE-CIC-IDS-2018/Wednesday-2...         91  6962593    strict           utf-8          LF               0
14  data/raw_improved/CSE-CIC-IDS-2018/Wednesday-2...         91  6568726    strict           utf-8          LF               0
15  data/raw_original/CIC-IDS-2017/Friday-WorkingH...         85   225745    strict           utf-8          LF               0
16  data/raw_original/CIC-IDS-2017/Friday-WorkingH...         85   286467    strict           utf-8        CRLF               0
17  data/raw_original/CIC-IDS-2017/Friday-WorkingH...         85   191033    strict           utf-8        CRLF               0
18  data/raw_original/CIC-IDS-2017/Monday-WorkingH...         85   529918    strict           utf-8          LF               0
19  data/raw_original/CIC-IDS-2017/Thursday-Workin...         85   288602    strict           utf-8        CRLF               0
20  data/raw_original/CIC-IDS-2017/Thursday-Workin...         85   458968    strict          cp1252        CRLF               0
21  data/raw_original/CIC-IDS-2017/Tuesday-Working...         85   445909    strict           utf-8        CRLF               0
22  data/raw_original/CIC-IDS-2017/Wednesday-worki...         85   692703    strict           utf-8        CRLF               0
23  data/raw_original/CSE-CIC-IDS-2018/Friday-02-0...         80  1048575    strict           utf-8        CRLF               0
24  data/raw_original/CSE-CIC-IDS-2018/Friday-16-0...         80  1048575    strict           utf-8          LF               0
25  data/raw_original/CSE-CIC-IDS-2018/Friday-23-0...         80  1048575    strict           utf-8          LF               0
26  data/raw_original/CSE-CIC-IDS-2018/Thuesday-20...         84  7948748    strict           utf-8       mixed               0
27  data/raw_original/CSE-CIC-IDS-2018/Thursday-01...         80   331125    strict           utf-8          LF               0
28  data/raw_original/CSE-CIC-IDS-2018/Thursday-15...         80  1048575    strict           utf-8          LF               0
29  data/raw_original/CSE-CIC-IDS-2018/Thursday-22...         80  1048575    strict           utf-8          LF               0
30  data/raw_original/CSE-CIC-IDS-2018/Wednesday-1...         80  1048575    strict           utf-8          LF               0
31  data/raw_original/CSE-CIC-IDS-2018/Wednesday-2...         80  1048575    strict           utf-8          LF               0
32  data/raw_original/CSE-CIC-IDS-2018/Wednesday-2...         80   613104    strict           utf-8          LF               0

In [3]:
# independent check: exact header names re-read from disk == saved schema
from src.audit.common import read_header
bad = [s['relpath'] for s in S if read_header(ROOT / s['relpath'])['names'] != s['header_names_exact']]
print('header mismatches:', bad)

header mismatches: []

In [4]:
L = pd.read_csv(R / 'label_distribution_by_dataset.csv', keep_default_na=False)
L[L.variant == 'improved'][['dataset_family','label','attempted_category','count','proportion']]

      dataset_family                                         label attempted_category     count    proportion
0       CIC-IDS-2017                                        BENIGN                 -1   1582566  7.536115e-01
1       CIC-IDS-2017                                      Portscan                 -1    159066  7.574658e-02
2       CIC-IDS-2017                                      DoS Hulk                 -1    158468  7.546181e-02
3       CIC-IDS-2017                                          DDoS                 -1     95144  4.530718e-02
4       CIC-IDS-2017                       Infiltration - Portscan                 -1     71767  3.417515e-02
5       CIC-IDS-2017                                 DoS GoldenEye                 -1      7567  3.603375e-03
6       CIC-IDS-2017                            Botnet - Attempted                  1      4067  1.936689e-03
7       CIC-IDS-2017                                   FTP-Patator                 -1      3972  1.891450e-03
8       CIC-IDS-2017                                 DoS Slowloris                 -1      3859  1.837640e-03
9       CIC-IDS-2017                                   SSH-Patator                 -1      2961  1.410016e-03
10      CIC-IDS-2017                  DoS Slowhttptest - Attempted                  6      2804  1.335253e-03
11      CIC-IDS-2017                              DoS Slowhttptest                 -1      1740  8.285809e-04
12      CIC-IDS-2017                     DoS Slowloris - Attempted                  0      1705  8.119140e-04
13      CIC-IDS-2017          Web Attack - Brute Force - Attempted                  0      1214  5.781018e-04
14      CIC-IDS-2017                                        Botnet                 -1       736  3.504802e-04
15      CIC-IDS-2017                  Web Attack - XSS - Attempted                  0       651  3.100035e-04
16      CIC-IDS-2017                          DoS Hulk - Attempted                  0       579  2.757174e-04
17      CIC-IDS-2017                  DoS Slowhttptest - Attempted                  0       563  2.680983e-04
18      CIC-IDS-2017                     DoS Slowloris - Attempted                  5       138  6.571504e-05
19      CIC-IDS-2017                     DoS GoldenEye - Attempted                  0        80  3.809567e-05
20      CIC-IDS-2017                      Web Attack - Brute Force                 -1        73  3.476230e-05
21      CIC-IDS-2017          Web Attack - Brute Force - Attempted                  4        71  3.380991e-05
22      CIC-IDS-2017                      Infiltration - Attempted                  0        42  2.000023e-05
23      CIC-IDS-2017                                  Infiltration                 -1        36  1.714305e-05
24      CIC-IDS-2017                       SSH-Patator - Attempted                  3        27  1.285729e-05
25      CIC-IDS-2017                              Web Attack - XSS                 -1        18  8.571527e-06
26      CIC-IDS-2017                    Web Attack - SQL Injection                 -1        13  6.190547e-06
27      CIC-IDS-2017                                    Heartbleed                 -1        11  5.238155e-06
28      CIC-IDS-2017                       FTP-Patator - Attempted                  0        10  4.761959e-06
29      CIC-IDS-2017          Web Attack - Brute Force - Attempted                  2         7  3.333371e-06
30      CIC-IDS-2017        Web Attack - SQL Injection - Attempted                  2         4  1.904784e-06
31      CIC-IDS-2017                  Web Attack - XSS - Attempted                  2         4  1.904784e-06
32      CIC-IDS-2017                      Infiltration - Attempted                  2         3  1.428588e-06
33      CIC-IDS-2017                     DoS Slowloris - Attempted                  2         3  1.428588e-06
34      CIC-IDS-2017                       FTP-Patator - Attempted                  2         2  9.523918e-07
35      CIC-IDS-2017                          DoS Hulk - Attempted                  4         2  9.523918e-07
36      CIC-IDS-2017        Web Attack - SQL Injection - Attempted                  0         1  4.761959e-07
37      CIC-IDS-2017                  DoS Slowhttptest - Attempted                  4         1  4.761959e-07
38      CIC-IDS-2017                     DoS Slowloris - Attempted                  4         1  4.761959e-07
55  CSE-CIC-IDS-2018                                        BENIGN                 -1  59353486  9.392096e-01
56  CSE-CIC-IDS-2018                                      DoS Hulk                 -1   1803160  2.853320e-02
57  CSE-CIC-IDS-2018                                     DDoS-HOIC                 -1   1082293  1.712620e-02
58  CSE-CIC-IDS-2018                    FTP-BruteForce - Attempted                  1    298844  4.728908e-03
59  CSE-CIC-IDS-2018                                DDoS-LOIC-HTTP                 -1    289328  4.578326e-03
60  CSE-CIC-IDS-2018                                   Botnet Ares                 -1    142921  2.261582e-03
61  CSE-CIC-IDS-2018                                SSH-BruteForce                 -1     94197  1.490573e-03
62  CSE-CIC-IDS-2018                  Infiltration - NMAP Portscan                 -1     89374  1.414254e-03
63  CSE-CIC-IDS-2018                                 DoS GoldenEye                 -1     22560  3.569894e-04
64  CSE-CIC-IDS-2018                                 DoS Slowloris                 -1      8490  1.343458e-04
65  CSE-CIC-IDS-2018                     DoS GoldenEye - Attempted                  4      4248  6.722035e-05
66  CSE-CIC-IDS-2018                                 DDoS-LOIC-UDP                 -1      2527  3.998725e-05
67  CSE-CIC-IDS-2018                     DoS Slowloris - Attempted                  0      2280  3.607872e-05
68  CSE-CIC-IDS-2018                       Botnet Ares - Attempted                  0       258  4.082592e-06
69  CSE-CIC-IDS-2018                     DDoS-LOIC-UDP - Attempted                  6       251  3.971824e-06
70  CSE-CIC-IDS-2018  Infiltration - Communication Victim Attacker                 -1       204  3.228096e-06
71  CSE-CIC-IDS-2018                      Web Attack - Brute Force                 -1       131  2.072944e-06
72  CSE-CIC-IDS-2018          Web Attack - Brute Force - Attempted                  5       126  1.993824e-06
73  CSE-CIC-IDS-2018                              Web Attack - XSS                 -1       113  1.788112e-06
74  CSE-CIC-IDS-2018                          DoS Hulk - Attempted                  0        86  1.360864e-06
75  CSE-CIC-IDS-2018               Infiltration - Dropbox Download                 -1        85  1.345040e-06
76  CSE-CIC-IDS-2018                     DoS GoldenEye - Attempted                  6        53  8.386720e-07
77  CSE-CIC-IDS-2018                              Web Attack - SQL                 -1        39  6.171360e-07
78  CSE-CIC-IDS-2018                    FTP-BruteForce - Attempted                  4        30  4.747200e-07
79  CSE-CIC-IDS-2018   Infiltration - Dropbox Download - Attempted                  4        28  4.430720e-07
80  CSE-CIC-IDS-2018                  Web Attack - SQL - Attempted                  2         8  1.265920e-07
81  CSE-CIC-IDS-2018          Web Attack - Brute Force - Attempted                  2         8  1.265920e-07
82  CSE-CIC-IDS-2018                  Web Attack - SQL - Attempted                  0         6  9.494400e-08
83  CSE-CIC-IDS-2018                       Botnet Ares - Attempted                  2         4  6.329600e-08
84  CSE-CIC-IDS-2018          Web Attack - Brute Force - Attempted                  0         3  4.747200e-08
85  CSE-CIC-IDS-2018                  Web Attack - XSS - Attempted                  2         2  3.164800e-08
86  CSE-CIC-IDS-2018                  Web Attack - XSS - Attempted                  0         1  1.582400e-08
87  CSE-CIC-IDS-2018                  Web Attack - XSS - Attempted                  3         1  1.582400e-08

In [5]:
pd.read_csv(R / 'label_vs_labelling_rules.csv').groupby(['dataset_family','status']).size()

dataset_family    status
CIC-IDS-2017      benign_default (label_rest_as_benign)     5
                  rule_and_data                            38
                  rule_matched_no_flows                     7
CSE-CIC-IDS-2018  benign_default (label_rest_as_benign)    10
                  rule_and_data                            47
                  rule_matched_no_flows                    11
dtype: int64

In [6]:
pd.read_csv(R / 'schema_diff_original_vs_improved.csv').groupby(['dataset_family','status']).size()

dataset_family    status
CIC-IDS-2017      added         7
                  removed       1
                  renamed      73
                  unchanged    11
CSE-CIC-IDS-2018  added         7
                  renamed      48
                  unchanged    36
dtype: int64