# 04 Original versus improved (Phase 4)
File- and distribution-level comparison, plus a row-matching feasibility test. Report: `reports/original_vs_improved.md`.

In [1]:
import sys, json
from pathlib import Path
import pandas as pd
ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT))
R = ROOT / "results/audit"
M = ROOT / "data/manifests"
pd.set_option("display.max_rows", 80); pd.set_option("display.max_columns", 40); pd.set_option("display.width", 200)
print("project root:", ROOT.name)

project root: research_paper

In [2]:
pd.read_csv(R / 'original_vs_improved_summary.csv')

,dataset_family,metric,original,improved,evidence,note
0,CIC-IDS-2017,files,8,5,schema_by_file.json,NaN
1,CIC-IDS-2017,rows (all),3119345,2099976,schema_by_file.json,NaN
2,CIC-IDS-2017,flows (excluding empty / header rows),2830743,2099976,label_distribution_by_dataset.csv,NaN
3,CIC-IDS-2017,benign share of flows,0.803004,0.753611,label_distribution_by_dataset.csv,NaN
4,CIC-IDS-2017,'Attempted' flows,0,11979,label_distribution_by_dataset.csv,class introduced by CNS2022
5,CIC-IDS-2017,"distinct (label, category) pairs",16,39,label_distribution_by_dataset.csv,NaN
6,CIC-IDS-2017,columns,85,91,schema_by_file.json,NaN
7,CIC-IDS-2017,timestamp format(s),%d/%m/%Y %H:%M | %d/%m/%Y %H:%M:%S,%Y-%m-%d %H:%M:%S.%f,schema_by_file.json,"original: local time, no timezone; improved: U..."
8,CIC-IDS-2017,non-finite rate values (Flow Bytes/s),2867,5,numeric_feature_summary.csv,NaN
9,CIC-IDS-2017,negative values in non-negative columns (cells),3510,781,numeric_feature_summary.csv,improved negatives are int16 header-length ove...
10,CIC-IDS-2017,constant columns,Bwd PSH Flags; Bwd URG Flags; Fwd Bytes/Bulk A...,none,numeric_feature_summary.csv,NaN
11,CIC-IDS-2017,data rows (excl. empty and embedded header rows),2830743,2099976,duplicates_by_file.csv,NaN
12,CIC-IDS-2017,exact duplicate rows (data rows; copies beyond...,203,0,duplicates_by_file.csv,NaN
13,CIC-IDS-2017,feature-identical rows (data rows; copies beyo...,308848,263004,duplicates_by_file.csv,NaN
14,CIC-IDS-2017,rows in label-conflict groups,7018,14140,duplicates_by_file.csv,NaN
15,CIC-IDS-2017,rows in benign/non-benign conflict groups,7018,22,duplicates_by_file.csv,NaN
16,CIC-IDS-2017,feature-identical share of data rows,0.109105,0.125241,duplicates_by_file.csv,NaN
17,CIC-IDS-2017,timestamp min .. max (as parsed),2017-07-03 01:00:01 .. 2017-07-07 12:59:00,2017-07-03 11:55:58.598308 .. 2017-07-07 20:02...,timestamp_quality.csv,"original clock is local, 12-hour without AM/PM..."
18,CIC-IDS-2017,row-level match: day pairs defensible,NaN,1/8,row_matching_feasibility.csv,"criteria: unique >= 0.9, ambiguous <= 0.02"
19,CIC-IDS-2017,timezone offset of original clock (5-tuple days),-3,UTC (DOCUMENTED),row_matching_feasibility.csv,NaN
20,CSE-CIC-IDS-2018,files,10,10,schema_by_file.json,NaN
21,CSE-CIC-IDS-2018,rows (all),16233002,63195145,schema_by_file.json,NaN
22,CSE-CIC-IDS-2018,flows (excluding empty / header rows),16232943,63195145,label_distribution_by_dataset.csv,NaN
23,CSE-CIC-IDS-2018,benign share of flows,0.8307,0.93921,label_distribution_by_dataset.csv,NaN
24,CSE-CIC-IDS-2018,'Attempted' flows,0,306237,label_distribution_by_dataset.csv,class introduced by CNS2022
25,CSE-CIC-IDS-2018,"distinct (label, category) pairs",16,33,label_distribution_by_dataset.csv,NaN
26,CSE-CIC-IDS-2018,columns,80; 84,91,schema_by_file.json,NaN
27,CSE-CIC-IDS-2018,timestamp format(s),%d/%m/%Y %H:%M:%S,%Y-%m-%d %H:%M:%S.%f,schema_by_file.json,"original: local time, no timezone; improved: U..."
28,CSE-CIC-IDS-2018,non-finite rate values (Flow Bytes/s),95760,57,numeric_feature_summary.csv,NaN
29,CSE-CIC-IDS-2018,negative values in non-negative columns (cells),106,27548,numeric_feature_summary.csv,improved negatives are int16 header-length ove...
30,CSE-CIC-IDS-2018,constant columns,Bwd PSH Flags; Bwd URG Flags; Fwd Bytes/Bulk A...,Bwd URG Flags,numeric_feature_summary.csv,NaN
31,CSE-CIC-IDS-2018,data rows (excl. empty and embedded header rows),16232943,63195145,duplicates_by_file.csv,NaN
32,CSE-CIC-IDS-2018,exact duplicate rows (data rows; copies beyond...,433195,0,duplicates_by_file.csv,NaN
33,CSE-CIC-IDS-2018,feature-identical rows (data rows; copies beyo...,4265470,17994469,duplicates_by_file.csv,NaN
34,CSE-CIC-IDS-2018,rows in label-conflict groups,423290,263772,duplicates_by_file.csv,NaN
35,CSE-CIC-IDS-2018,rows in benign/non-benign conflict groups,170766,263772,duplicates_by_file.csv,NaN
36,CSE-CIC-IDS-2018,feature-identical share of data rows,0.262766,0.284744,duplicates_by_file.csv,NaN
37,CSE-CIC-IDS-2018,timestamp min .. max (as parsed),1970-01-05 03:01:17 .. 2018-03-02 12:59:59,2018-02-14 12:28:07.743746 .. 2018-03-03 00:39...,timestamp_quality.csv,"original clock is local, 12-hour without AM/PM..."
38,CSE-CIC-IDS-2018,row-level match: day pairs defensible,NaN,0/10,row_matching_feasibility.csv,"criteria: unique >= 0.9, ambiguous <= 0.02"
39,CSE-CIC-IDS-2018,timezone offset of original clock (5-tuple days),-4,UTC (DOCUMENTED),row_matching_feasibility.csv,NaN

In [3]:
pd.read_csv(R / 'label_family_comparison.csv')

,dataset_family,family,original_count,original_share,improved_count_not_attempted,improved_count_attempted,improved_share_not_attempted,improved_total_vs_original_ratio,improved_not_attempted_vs_original_ratio,comparison_level
0,CIC-IDS-2017,benign,2273097,0.728710,1582566,0,7.536115e-01,0.6962,0.6962,label-family counts (not row correspondence)
1,CIC-IDS-2017,botnet,1966,0.000630,736,4067,3.504800e-04,2.4430,0.3744,label-family counts (not row correspondence)
2,CIC-IDS-2017,ddos_loic,128027,0.041043,95144,0,4.530718e-02,0.7432,0.7432,label-family counts (not row correspondence)
3,CIC-IDS-2017,dos_goldeneye,10293,0.003300,7567,80,3.603370e-03,0.7429,0.7352,label-family counts (not row correspondence)
4,CIC-IDS-2017,dos_hulk,231073,0.074077,158468,581,7.546181e-02,0.6883,0.6858,label-family counts (not row correspondence)
5,CIC-IDS-2017,dos_slowhttptest,5499,0.001763,1740,3368,8.285800e-04,0.9289,0.3164,label-family counts (not row correspondence)
6,CIC-IDS-2017,dos_slowloris,5796,0.001858,3859,1847,1.837640e-03,0.9845,0.6658,label-family counts (not row correspondence)
7,CIC-IDS-2017,ftp_bruteforce,7938,0.002545,3972,12,1.891450e-03,0.5019,0.5004,label-family counts (not row correspondence)
8,CIC-IDS-2017,heartbleed,11,0.000004,11,0,5.240000e-06,1.0000,1.0000,label-family counts (not row correspondence)
9,CIC-IDS-2017,infiltration,36,0.000012,71803,45,3.419230e-02,1995.7778,1994.5278,label-family counts (not row correspondence)
10,CIC-IDS-2017,portscan,158930,0.050950,159066,0,7.574658e-02,1.0009,1.0009,label-family counts (not row correspondence)
11,CIC-IDS-2017,ssh_bruteforce,5897,0.001890,2961,27,1.410020e-03,0.5067,0.5021,label-family counts (not row correspondence)
12,CIC-IDS-2017,unlabelled_empty_row,288602,0.092520,0,0,0.000000e+00,0.0000,0.0000,label-family counts (not row correspondence)
13,CIC-IDS-2017,web_bruteforce,1507,0.000483,73,1292,3.476000e-05,0.9058,0.0484,label-family counts (not row correspondence)
14,CIC-IDS-2017,web_sqli,21,0.000007,13,5,6.190000e-06,0.8571,0.6190,label-family counts (not row correspondence)
15,CIC-IDS-2017,web_xss,652,0.000209,18,655,8.570000e-06,1.0322,0.0276,label-family counts (not row correspondence)
16,CSE-CIC-IDS-2018,benign,13484708,0.830697,59353486,0,9.392096e-01,4.4015,4.4015,label-family counts (not row correspondence)
17,CSE-CIC-IDS-2018,botnet,286191,0.017630,142921,262,2.261580e-03,0.5003,0.4994,label-family counts (not row correspondence)
18,CSE-CIC-IDS-2018,ddos_hoic,686012,0.042260,1082293,0,1.712620e-02,1.5777,1.5777,label-family counts (not row correspondence)
19,CSE-CIC-IDS-2018,ddos_loic_http,576191,0.035495,289328,0,4.578330e-03,0.5021,0.5021,label-family counts (not row correspondence)
20,CSE-CIC-IDS-2018,ddos_loic_udp,1730,0.000107,2527,251,3.999000e-05,1.6058,1.4607,label-family counts (not row correspondence)
21,CSE-CIC-IDS-2018,dos_goldeneye,41508,0.002557,22560,4301,3.569900e-04,0.6471,0.5435,label-family counts (not row correspondence)
22,CSE-CIC-IDS-2018,dos_hulk,461912,0.028455,1803160,86,2.853320e-02,3.9039,3.9037,label-family counts (not row correspondence)
23,CSE-CIC-IDS-2018,dos_slowhttptest,139890,0.008618,0,0,0.000000e+00,0.0000,0.0000,label-family counts (not row correspondence)
24,CSE-CIC-IDS-2018,dos_slowloris,10990,0.000677,8490,2280,1.343500e-04,0.9800,0.7725,label-family counts (not row correspondence)
25,CSE-CIC-IDS-2018,embedded_header_row,59,0.000004,0,0,0.000000e+00,0.0000,0.0000,label-family counts (not row correspondence)
26,CSE-CIC-IDS-2018,ftp_bruteforce,193360,0.011912,0,298874,0.000000e+00,1.5457,0.0000,label-family counts (not row correspondence)
27,CSE-CIC-IDS-2018,infiltration,161934,0.009976,89663,28,1.418830e-03,0.5539,0.5537,label-family counts (not row correspondence)
28,CSE-CIC-IDS-2018,ssh_bruteforce,187589,0.011556,94197,0,1.490570e-03,0.5021,0.5021,label-family counts (not row correspondence)
29,CSE-CIC-IDS-2018,web_bruteforce,611,0.000038,131,137,2.070000e-06,0.4386,0.2144,label-family counts (not row correspondence)
30,CSE-CIC-IDS-2018,web_sqli,87,0.000005,39,14,6.200000e-07,0.6092,0.4483,label-family counts (not row correspondence)
31,CSE-CIC-IDS-2018,web_xss,230,0.000014,113,4,1.790000e-06,0.5087,0.4913,label-family counts (not row correspondence)

In [4]:
FD = pd.read_csv(R / 'feature_distribution_comparison.csv')
FD[['dataset_family','column','original_q50','improved_q50','rel_change_q50','original_q99','improved_q99','original_nonfinite','improved_nonfinite']].head(40)

   dataset_family                  column  original_q50  improved_q50  rel_change_q50  original_q99  improved_q99  original_nonfinite  improved_nonfinite
0    CIC-IDS-2017          ACK Flag Count      0.000000      0.763205             NaN  1.000000e+00  1.349764e+02                 0.0                 0.0
1    CIC-IDS-2017              Active Max      0.000000      0.000000             NaN  4.228879e+06  5.399390e+06                 0.0                 0.0
2    CIC-IDS-2017             Active Mean      0.000000      0.000000             NaN  2.307002e+06  2.969327e+06                 0.0                 0.0
3    CIC-IDS-2017              Active Min      0.000000      0.000000             NaN  1.543213e+06  2.135818e+06                 0.0                 0.0
4    CIC-IDS-2017              Active Std      0.000000      0.000000             NaN  1.132196e+06  1.581225e+06                 0.0                 0.0
5    CIC-IDS-2017     Average Packet Size     72.724400     81.100923        0.115182  1.454435e+03  1.044016e+03                 0.0                 0.0
6    CIC-IDS-2017       Bwd Bulk Rate Avg      0.000000      0.000000             NaN  0.000000e+00  4.495032e+07                 0.0                 0.0
7    CIC-IDS-2017      Bwd Bytes/Bulk Avg      0.000000      0.000000             NaN  0.000000e+00  5.074325e+04                 0.0                 0.0
8    CIC-IDS-2017       Bwd Header Length     40.000000     20.000000       -0.500000  1.602999e+03  2.001615e+03                 0.0                 0.0
9    CIC-IDS-2017             Bwd IAT Max      3.000000     47.945610       14.981870  9.867279e+07  7.352259e+07                 0.0                 0.0
10   CIC-IDS-2017            Bwd IAT Mean      3.000000     47.822336       14.940779  5.373447e+07  6.013851e+07                 0.0                 0.0
11   CIC-IDS-2017             Bwd IAT Min      1.274941      3.000000        1.353049  4.724516e+07  5.653592e+07                 0.0                 0.0
12   CIC-IDS-2017             Bwd IAT Std      0.000000      0.000000             NaN  3.935608e+07  2.347309e+07                 0.0                 0.0
13   CIC-IDS-2017           Bwd IAT Total      3.000000     47.811564       14.937188  1.168955e+08  1.179607e+08                 0.0                 0.0
14   CIC-IDS-2017      Bwd Init Win Bytes     -0.963811      0.000000        1.000000  4.639083e+04  2.910825e+04                 0.0                 0.0
15   CIC-IDS-2017           Bwd PSH Flags      0.000000      0.000000             NaN  0.000000e+00  2.162349e+01                 0.0                 0.0
16   CIC-IDS-2017   Bwd Packet Length Max     79.767070    128.653098        0.612860  9.381417e+03  1.013803e+04                 0.0                 0.0
17   CIC-IDS-2017  Bwd Packet Length Mean     73.134844    114.820570        0.569984  2.501652e+03  2.781460e+03                 0.0                 0.0
18   CIC-IDS-2017   Bwd Packet Length Min      0.576773      0.001466       -0.997459  2.517857e+02  2.686673e+02                 0.0                 0.0
19   CIC-IDS-2017   Bwd Packet Length Std      0.000000      0.000000             NaN  4.186298e+03  4.379315e+03                 0.0                 0.0
20   CIC-IDS-2017     Bwd Packet/Bulk Avg      0.000000      0.000000             NaN  0.000000e+00  2.988431e+01                 0.0                 0.0
21   CIC-IDS-2017           Bwd Packets/s     19.799310     32.649543        0.649024  7.599231e+04  5.738541e+04                 0.0                 0.0
22   CIC-IDS-2017           Bwd RST Flags           NaN      0.000000             NaN           NaN  2.000000e+00                 NaN                 NaN
23   CIC-IDS-2017    Bwd Segment Size Avg     73.134844    114.820570        0.569984  2.501652e+03  2.781460e+03                 0.0                 0.0
24   CIC-IDS-2017           Bwd URG Flags      0.000000      0.000000             NaN  0.000000e+00  0.000000e+00                 0.0                 0.0
25   CIC-IDS-2017          CWR Flag Count      0.000000      0.000000             NaN  0.000000e+00  0.000000e+00                 0.0                 0.0
26   CIC-IDS-2017           Down/Up Ratio      1.000000      1.000000        0.000000  2.521716e+00  1.541423e+00                 0.0                 0.0
27   CIC-IDS-2017                Dst Port     80.000000     80.000000        0.000000  6.160424e+04  3.674693e+04                 0.0                 0.0
28   CIC-IDS-2017          ECE Flag Count      0.000000      0.000000             NaN  0.000000e+00  0.000000e+00                 0.0                 0.0
29   CIC-IDS-2017          FIN Flag Count      0.000000      0.000000             NaN  1.000000e+00  3.137082e+00                 0.0                 0.0
30   CIC-IDS-2017      FWD Init Win Bytes    251.458937    690.941666        1.747732  6.553500e+04  6.553500e+04                 0.0                 0.0
31   CIC-IDS-2017            Flow Bytes/s   4596.672202   3859.166885       -0.160443  1.422719e+07  2.810497e+06              2867.0                 5.0
32   CIC-IDS-2017           Flow Duration  31987.725378  63756.919249        0.993168  1.177609e+08  1.181188e+08                 0.0                 0.0
33   CIC-IDS-2017            Flow IAT Max  30991.792239  51914.879019        0.675117  9.980775e+07  7.385134e+07                 0.0                 0.0
34   CIC-IDS-2017           Flow IAT Mean  12140.707015  18897.167734        0.556513  2.072130e+07  2.186210e+07                 0.0                 0.0
35   CIC-IDS-2017            Flow IAT Min      4.000993      3.000000       -0.250186  6.251628e+05  3.062522e+05                 0.0                 0.0
36   CIC-IDS-2017            Flow IAT Std    189.155658  16035.091207       83.771936  3.372896e+07  3.659306e+07                 0.0                 0.0
37   CIC-IDS-2017          Flow Packets/s    110.160769     73.157608       -0.335901  1.648439e+06  4.993352e+05              2867.0                 5.0
38   CIC-IDS-2017       Fwd Act Data Pkts      1.000000      1.000000        0.000000  2.764019e+01  1.883713e+01                 0.0                 0.0
39   CIC-IDS-2017       Fwd Bulk Rate Avg      0.000000      0.000000             NaN  0.000000e+00  1.995916e+05                 0.0                 0.0

In [5]:
pd.read_csv(R / 'row_matching_feasibility.csv')[['dataset_family','original_file','improved_file','best_offset_hours_added_to_improved_utc','unique_coverage','ambiguous_share','defensible_for_row_level']]

      dataset_family                                      original_file             improved_file  best_offset_hours_added_to_improved_utc  unique_coverage  ambiguous_share  defensible_for_row_level
0       CIC-IDS-2017                  Monday-WorkingHours.pcap_ISCX.csv                monday.csv                                       -3           0.7276           0.0002                     False
1       CIC-IDS-2017                 Tuesday-WorkingHours.pcap_ISCX.csv               tuesday.csv                                       -3           0.7948           0.0011                     False
2       CIC-IDS-2017               Wednesday-workingHours.pcap_ISCX.csv             wednesday.csv                                       -3           0.8653           0.0006                     False
3       CIC-IDS-2017  Thursday-WorkingHours-Morning-WebAttacks.pcap_...              thursday.csv                                       -3           0.8066           0.0003                     False
4       CIC-IDS-2017  Thursday-WorkingHours-Afternoon-Infilteration....              thursday.csv                                       -3           0.8233           0.0245                     False
5       CIC-IDS-2017          Friday-WorkingHours-Morning.pcap_ISCX.csv                friday.csv                                       -3           0.8157           0.0029                     False
6       CIC-IDS-2017  Friday-WorkingHours-Afternoon-PortScan.pcap_IS...                friday.csv                                       -3           0.9136           0.0027                      True
7       CIC-IDS-2017   Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv                friday.csv                                       -3           0.7984           0.0132                     False
8   CSE-CIC-IDS-2018    Friday-02-03-2018_TrafficForML_CICFlowMeter.csv     Friday-02-03-2018.csv                                       -4           0.0046           0.8614                     False
9   CSE-CIC-IDS-2018    Friday-16-02-2018_TrafficForML_CICFlowMeter.csv     Friday-16-02-2018.csv                                       -4           0.0001           0.5699                     False
10  CSE-CIC-IDS-2018    Friday-23-02-2018_TrafficForML_CICFlowMeter.csv     Friday-23-02-2018.csv                                       -4           0.0062           0.7778                     False
11  CSE-CIC-IDS-2018  Thuesday-20-02-2018_TrafficForML_CICFlowMeter.csv    Tuesday-20-02-2018.csv                                       -4           0.7830           0.0010                     False
12  CSE-CIC-IDS-2018  Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv   Thursday-01-03-2018.csv                                       -4           0.0334           0.8037                     False
13  CSE-CIC-IDS-2018  Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv   Thursday-15-02-2018.csv                                       -4           0.0067           0.8437                     False
14  CSE-CIC-IDS-2018  Thursday-22-02-2018_TrafficForML_CICFlowMeter.csv   Thursday-22-02-2018.csv                                       -4           0.0055           0.7882                     False
15  CSE-CIC-IDS-2018  Wednesday-14-02-2018_TrafficForML_CICFlowMeter...  Wednesday-14-02-2018.csv                                       -4           0.0043           0.9004                     False
16  CSE-CIC-IDS-2018  Wednesday-21-02-2018_TrafficForML_CICFlowMeter...  Wednesday-21-02-2018.csv                                       -4           0.0014           0.6577                     False
17  CSE-CIC-IDS-2018  Wednesday-28-02-2018_TrafficForML_CICFlowMeter...  Wednesday-28-02-2018.csv                                       -4           0.0466           0.8074                     False

In [6]:
tm = R / 'label_transition_matrix.csv'
t = pd.read_csv(tm)
print(len(t), 'rows') ; t.head(40)

4 rows

  dataset_family                                      original_file improved_file original_label      improved_label  n_uniquely_matched_flows                                          scope
0   CIC-IDS-2017  Friday-WorkingHours-Afternoon-PortScan.pcap_IS...    friday.csv         BENIGN              BENIGN                    103009  unique matches only (91.36% of original rows)
1   CIC-IDS-2017  Friday-WorkingHours-Afternoon-PortScan.pcap_IS...    friday.csv         BENIGN  Botnet - Attempted                         5  unique matches only (91.36% of original rows)
2   CIC-IDS-2017  Friday-WorkingHours-Afternoon-PortScan.pcap_IS...    friday.csv       PortScan            Portscan                    158702  unique matches only (91.36% of original rows)
3   CIC-IDS-2017  Friday-WorkingHours-Afternoon-PortScan.pcap_IS...    friday.csv       PortScan              BENIGN                        13  unique matches only (91.36% of original rows)